table 'Measures Table'
	lineageTag: 6dfe0fd8-95c3-4411-98ce-5e197ef1e9f9

	measure 'Total Quantity' =
			
			SUM('Sales by Store'[quantity_sold])
		formatString: #,0
		displayFolder: Sales
		lineageTag: d65f2167-a9b4-474a-8bb6-2df37099c851

	measure 'Total Sales' =
			
			SUMX('Sales by Store', 'Sales by Store'[quantity_sold]*'Sales by Store'[unit_price])
		formatString: #,0
		displayFolder: Sales
		lineageTag: 72cb63ad-c0e6-41e4-a68f-e20a60d7d497

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WKk7MLchJVYqNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

