table 'Product Lookup'
	lineageTag: 56d79f9e-15d2-4174-8d18-67763361863f

	column product_id
		dataType: string
		lineageTag: 0f15c885-3e09-4c3c-840f-5839ff116530
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_group
		dataType: string
		lineageTag: 8b267881-9031-4ce0-ba54-c481013ced44
		summarizeBy: none
		sourceColumn: product_group

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: a1126e22-ccd2-4b39-b3fc-a94cffd64b61
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column product_type
		dataType: string
		lineageTag: 2f92d00f-8b89-4e72-9d3e-3c83d3a6e85a
		summarizeBy: none
		sourceColumn: product_type

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: f1eb2d74-84ea-46de-a37d-77cdddf3f2e3
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column product_description
		dataType: string
		lineageTag: 0771dd77-7029-4755-a79a-a19adb06808f
		summarizeBy: none
		sourceColumn: product_description

		annotation SummarizationSetBy = Automatic

	column unit_of_measure
		dataType: string
		lineageTag: 614a34b6-a29c-4ec0-8d43-3e7edca4fddf
		summarizeBy: none
		sourceColumn: unit_of_measure

		annotation SummarizationSetBy = Automatic

	column current_cost
		dataType: string
		lineageTag: 3751f102-2dc7-4a5a-ae95-b416519a49cd
		summarizeBy: none
		sourceColumn: current_cost

		annotation SummarizationSetBy = Automatic

	column current_wholesale_price
		dataType: string
		lineageTag: 395b33d5-d599-404b-b6be-353f171c95cc
		summarizeBy: none
		sourceColumn: current_wholesale_price

		annotation SummarizationSetBy = Automatic

	column current_retail_price
		dataType: string
		lineageTag: 065df17e-1d51-4676-b139-a48d299e4d2f
		summarizeBy: none
		sourceColumn: current_retail_price

		annotation SummarizationSetBy = Automatic

	column tax_exempt_yn
		dataType: string
		lineageTag: 3fc00502-55eb-4784-87af-c89ac615834d
		summarizeBy: none
		sourceColumn: tax_exempt_yn

		annotation SummarizationSetBy = Automatic

	column promo_yn
		dataType: string
		lineageTag: bafe70ba-0e58-48ad-a760-949bb5ba4226
		summarizeBy: none
		sourceColumn: promo_yn

		annotation SummarizationSetBy = Automatic

	column new_product_yn
		dataType: string
		lineageTag: bdf4ef1b-8e1a-4435-b5eb-13aa1a67e2ae
		summarizeBy: none
		sourceColumn: new_product_yn

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: string
		lineageTag: c9b74f9a-4b64-4844-8bab-12d64de29918
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 'Product Lookup' = m
		mode: import
		source =
				let
				    Bron = Csv.Document(File.Contents("C:\Users\flawl\Documents\Udemy\Power BI\Course\Advanced+DAX+Data+Files\Advanced DAX Data Files\Product Lookup.csv"),[Delimiter=",", Columns=14, QuoteStyle=QuoteStyle.None]),
				    #"Headers met verhoogd niveau" = Table.PromoteHeaders(Bron, [PromoteAllScalars=true])
				in
				    #"Headers met verhoogd niveau"

	annotation PBI_NavigationStepName = Navigatie

	annotation PBI_ResultType = Table

